version: "3.9"

services:
  web:
    build:
      dockerfile: ./build/invoices/Dockerfile
      context: .
    command: gunicorn invoice_project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/home/app
      - static_volume:/home/app/static
      - media_volume:/home/app/media
    env_file:
      - .env
    depends_on:
      - db
  db:
    build:
      context: ./build/db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  nginx:
    build:
      context: ./build/nginx
    restart: unless-stopped
    volumes:
      - static_volume:/home/app/static
      - media_volume:/home/app/media
      - certbot_etc:/etc/letsencrypt
      - certbot_var:/var/lib/letsencrypt
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume:
  certbot_etc:
  certbot_var:
