version: "3.9"

services:
  web:
    build:
      dockerfile: docker/invoices/Dockerfile
      context: .
    command: sh -c "python manage.py makemigrations && python manage.py migrate --noinput && python manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - .:/home/app
      - static_volume:/home/app/static
      - media_volume:/home/app/media
    env_file:
      - dev.env
    depends_on:
      - db
  db:
    build:
      context: docker/db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  nginx:
    build:
      context: docker/nginx
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    volumes:
      - static_volume:/home/app/static
      - media_volume:/home/app/media
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume:
