# Generated by Django 4.2.5 on 2023-10-30 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_alter_invoice_invoice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='customer_phone',
            field=models.TextField(blank=True, null=True),
        ),
    ]
