# Generated by Django 4.2.5 on 2023-10-12 21:33

import companies.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('logo', models.ImageField(upload_to=companies.models.path_and_rename)),
                ('color', models.CharField(blank=True, max_length=25, null=True)),
                ('billing_address', models.TextField()),
                ('bank_name', models.CharField(max_length=30)),
                ('account_number', models.CharField(max_length=20)),
                ('branch_name', models.CharField(max_length=30)),
                ('branch_code', models.CharField(max_length=10)),
                ('branch_code_electronic', models.CharField(blank=True, max_length=10, null=True)),
                ('contact_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('currency', models.CharField(choices=[('ZAR', 'South African Rand'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound')], default='ZAR', max_length=3)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'companies',
            },
        ),
    ]
